# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SJNetWorking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SJNetWorking
  pod 'AFNetworking'
  #:inhibit_warnings => true
  pod 'YYCache'
  
  
  target 'SJNetWorkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJNetWorkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
